import { ProducerType } from "@/types/producers-props";

export const PRODUCERS: ProducerType[] = [
  {
    id: 1,
    type: "Legumes",
    name: "Horta da Barca",
    address: {
      street: "Rua da Igreja",
      number: "12",
      city: "Ponte da Barca",
      state: "Viana do Castelo",
      zipCode: "4980-020",
      coords: { lat: 41.8048, lng: -8.4185 },
    },
    phone: "",
    email: "",
    website: "",
    description: "",
    image: "",
    socialMedia: [],
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 2,
    type: "Vinho",
    name: "Quinta do Vale Verde",
    address: {
      street: "Rua do Souto",
      number: "45",
      city: "Ponte da Barca",
      state: "Viana do Castelo",
      zipCode: "4980-030",
      coords: { lat: 41.8072, lng: -8.4149 },
    },
    phone: "",
    email: "",
    website: "",
    description: "",
    image: "",
    socialMedia: [],
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 3,
    type: ["Fruta & Legumes"],
    name: "Pomar do Lima",
    address: {
      street: "Rua das Flores",
      number: "8",
      city: "Ponte da Barca",
      state: "Viana do Castelo",
      zipCode: "4980-015",
      coords: { lat: 41.8029, lng: -8.4202 },
    },
    phone: "",
    email: "",
    website: "",
    description: "",
    image: "",
    socialMedia: [],
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 4,
    type: "Mel",
    name: "Mel Serra Amarela",
    address: {
      street: "Caminho da Serra",
      number: "3",
      city: "Ponte da Barca",
      state: "Viana do Castelo",
      zipCode: "4980-025",
      coords: { lat: 41.8091, lng: -8.4127 },
    },
    phone: "",
    email: "",
    website: "",
    description: "",
    image: "",
    socialMedia: [],
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 5,
    type: "Queijo",
    name: "Queijaria Tradicional",
    address: {
      street: "Rua do Rio",
      number: "27",
      city: "Ponte da Barca",
      state: "Viana do Castelo",
      zipCode: "4980-018",
      coords: { lat: 41.8015, lng: -8.4161 },
    },
    phone: "",
    email: "",
    website: "",
    description: "",
    image: "",
    socialMedia: [],
    createdAt: "",
    updatedAt: "",
  },
];
