import { ProducerType } from "@/types/producers-props";

export const PRODUCERS: ProducerType[] = [
  {
    id: 1,
    type: "Legumes",
    name: "Producer One",
    address: {
      street: "Main St",
      number: "123",
      city: "Barcelona",
      state: "Barcelona",
      zipCode: "12345",
      coords: { lat: 41.806, lng: -8.42 },
    },
    phone: "",
    email: "",
    website: "",
    description: "",
    image: "",
    socialMedia: [],
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 2,
    type: "Vinho",
    name: "Producer Two",
    address: {
      street: "Main St",
      number: "123",
      city: "Barcelona",
      state: "Barcelona",
      zipCode: "12345",
      coords: { lat: 31.806, lng: -6.42 },
    },
    phone: "",
    email: "",
    website: "",
    description: "",
    image: "",
    socialMedia: [],
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 3,
    type: "Fruta",
    name: "Producer Three",
    address: {
      street: "Main St",
      number: "123",
      city: "Barcelona",
      state: "Barcelona",
      zipCode: "12345",
      coords: { lat: 31.806, lng: -6.42 },
    },
    phone: "",
    email: "",
    website: "",
    description: "",
    image: "",
    socialMedia: [],
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 4,
    type: "Mel",
    name: "Producer Four",
    address: {
      street: "Main St",
      number: "123",
      city: "Barcelona",
      state: "Barcelona",
      zipCode: "12345",
      coords: { lat: 31.806, lng: -6.42 },
    },
    phone: "",
    email: "",
    website: "",
    description: "",
    image: "",
    socialMedia: [],
    createdAt: "",
    updatedAt: "",
  },
];
